### ISSUE TITLE
Support optional static typing

### ISSUE THREAD

**Issue by zyebytevt** [AuburnSounds/wren-port#7]
Hello! Definitely first and foremost, amazing port of Wren!

Just asking out of curiosity, is it maybe possible to implement optional static typing (or a linter for that)? I imagine this to be somewhat more difficult to implement.

**Comment by p0nce** [comment]
Wren is a one-pass compiler witthout AST. it generates the VM IR while parsing. Hence it needs no forward declaration, since there is nothing to check. If you were to modify Wren to have type annotations, you would probably need an AST to do multiple passes. I ported the codebase, but do not understand it completely, so it's 100% unlikely that I would do that.
Lua is also the same AFAIK (no AST) so it probably has a runtime cost.

**Comment by p0nce** [comment]
I'm closing this issue :) as adding this would be a half-rewrite of Wren probably.

**Comment by Yorizuka** [comment]
Not directly related to wren-port, but maybe useful to people looking at this issue to note that there is a typescript like tool for lua https://github.com/teal-language/tl

**Comment by p0nce** [comment]
Also luau: https://luau-lang.org/
